-- ###########################################################
-- ###    Specific configurations for the local machine    ###
-- ### This file is sourced by the ~/.config/nvim/init.lua ###
-- ###########################################################
