#!/usr/bin/env bash
############################################
###       THIS CONFIG IS SYMLINKED       ###
###    DONT' ENTER ANY SENSITIVE INFO    ###
###                                      ###
###  USE LOCAL CONFIG FOR MODIFICATIONS  ###
### UNLESS CHANGES WILL BECOME PERMANENT ###
############################################

#if [[ "${OSTYPE}" == "linux-gnu" ]]; then
if [[ "${OSTYPE}" == "darwin"* ]]; then
    # Toggle hidden files
    # NOTE: Looks like there is a built-in shortcut 'CMD + Shift + . ', i.e. 'CMD + >' to do this as well
    alias show='defaults write com.apple.finder AppleShowAllFiles YES;killall Finder /System/Library/CoreServices/Finder.app'
    alias hide='defaults write com.apple.finder AppleShowAllFiles NO;killall Finder /System/Library/CoreServices/Finder.app'
fi

alias vim="nvim -c 'FzfLua git_files'"
# alias vim='/Users/ilyakisil/opt/nvim/v0.8.0-dev+547-ge837f29ce/bin/nvim'
alias vvim='\vim'
alias :q='exit'
alias :wq='exit'
alias import-secrets="source $ZSHENV_SECRETS"

alias ..='cd ..'

alias clc='clear'

alias la='ls --color=auto -la'

alias grep='grep --color=auto'

alias gh-doctoc='doctoc --github --title "$(echo "\n## Table of Contents\nGenerated with [DocToc](https://github.com/thlorenz/doctoc)\n\nLast Update: `date +%Y-%m-%d`")"'
alias bb-doctoc='doctoc --bitbucket --title "$(echo "\n## Table of Contents\nGenerated with [DocToc](https://github.com/thlorenz/doctoc)\n\nLast Update: `date +%Y-%m-%d`")"'


ALIASES_LOCAL="${HOME}/.aliases-local"
if [[ -f "${ALIASES_LOCAL}" ]]; then
    source "${ALIASES_LOCAL}"
fi
