#!/usr/bin/env bash
### Quick locations
alias gh='cd ~/GitHub'
alias gl='cd ~/GitLab'
alias bb='cd ~/BitBucket'

### Python
alias sa='conda activate'
alias sd='conda deactivate'
alias jl='jupyter-lab'

### Matlab
alias mat='matlab -nodisplay -nosplash'

