" ############################################
" ###       THIS CONFIG IS SYMLINKED       ###
" ###    DONT' ENTER ANY SENSITIVE INFO    ###
" ###                                      ###
" ###  USE LOCAL CONFIG FOR MODIFICATIONS  ###
" ### UNLESS CHANGES WILL BECOME PERMANENT ###
" ############################################

" ============================================================================
" LOAD VM INVARIANT CONFIGURATIONS
" ============================================================================
if has("nvim")
    let $__VIM_DOTFILES_HOME = $HOME.'/.config/nvim'
    let __local_configs_path = $__VIM_DOTFILES_HOME.'init-local.vim'

    source $__VIM_DOTFILES_HOME/init-nvim-specific.vim
else
    let $__VIM_DOTFILES_HOME = $HOME.'/.vim'
    let __local_configs_path = $__VIM_DOTFILES_HOME.'vimrc-local'
endif

source $__VIM_DOTFILES_HOME/general/settings.vim
source $__VIM_DOTFILES_HOME/general/mappings.vim
source $__VIM_DOTFILES_HOME/general/functions.vim
source $__VIM_DOTFILES_HOME/vim-plug/plugins.vim

"source $__VIM_DOTFILES_HOME/themes/onedark.vim
source $__VIM_DOTFILES_HOME/themes/gruvbox.vim
source $__VIM_DOTFILES_HOME/themes/airline.vim
source $__VIM_DOTFILES_HOME/themes/vim-devicons.vim

source $__VIM_DOTFILES_HOME/vim-plug/configs/nerdtree.vim
source $__VIM_DOTFILES_HOME/vim-plug/configs/fzf.vim
source $__VIM_DOTFILES_HOME/vim-plug/configs/coc.vim
source $__VIM_DOTFILES_HOME/vim-plug/configs/youcompleteme.vim
source $__VIM_DOTFILES_HOME/vim-plug/configs/vim-autoclose.vim
source $__VIM_DOTFILES_HOME/vim-plug/configs/sneak.vim
source $__VIM_DOTFILES_HOME/vim-plug/configs/vim-snippets.vim


" ============================================================================
" LOAD VM SPECIFIC (LOCAL) CONFIGURATIONS
" ============================================================================
if filereadable(expand(__local_configs_path))
    execute "source " . __local_configs_path
endif
