#!/usr/bin/env bash
# vim: ft=sh

#####################################################
### Specific configurations for the local machine ###
###     This file is sourced by the ~/.zshrc      ###
###                                               ###
###     All aliases should go into dedicated      ###
###   file, i.e. ~/.aliases or ~/.aliases-local   ###
#####################################################

ZSH_CUSTOM="${HOME}/.config/zsh/custom"

###------------------------------    THEME   -------------------------------###
### Bundled with oh-my-zsh
#ZSH_THEME="agnoster"

### External theme for zsh
# Although it is not required, but Powerline10k can take advantage of Meslo Nerd Font
# https://github.com/romkatv/powerlevel10k#fonts
ZSH_THEME="powerlevel10k/powerlevel10k"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r '${XDG_CACHE_HOME:-${HOME}/.cache}/p10k-instant-prompt-${(%):-%n}.zsh' ]]; then
  source '${XDG_CACHE_HOME:-${HOME}/.cache}/p10k-instant-prompt-${(%):-%n}.zsh'
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
P10K_CONFIG=${HOME}/.p10k.zsh
[[ ! -f ${P10K_CONFIG} ]] || source ${P10K_CONFIG}



###---------------------------   ZSH PLUGINS   -----------------------------###
ZSH_PLUGINS=(
    # tmux
    # zsh-autosuggestions  # Don't really like it. Better to use 'fzf'
    # gcloud               # Relies on google-sdk being in certain locations, e.g. $HOME
    docker
    docker-compose
)

# This is tailored specifically for the p10k prompt scheme
#ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#595858,bg=underline"



###----------------------------    CLI TOOLS   -----------------------------###
if command -v fzf 1>/dev/null 2>&1; then
    ZSH_PLUGINS=(${ZSH_PLUGINS} fzf)

    FZF_ORANGE_COLOR="#CC7832"
    FZF_YELLOW_COLOR="#E5C07B"
    FZF_GRAY_COLOR="#46484A"

    FZF_OPTS="
      --height 40%
      --inline-info
      --layout=reverse
      --no-bold
      --cycle
    "

    # For list of things see 'AVAILABLE ACTIONS' in 'man fzf'
    FZF_BINDINGS='
      --bind=ctrl-e:up
      --bind=ctrl-n:down
      --bind=ctrl-o:toggle-all
      --bind=ctrl-d:preview-half-page-down
      --bind=ctrl-u:preview-half-page-up
      --bind=ctrl-p:toggle-preview
      --bind=ctrl-l:clear-query
    '

    # https://github.com/junegunn/fzf/blob/master/README-VIM.md#explanation-of-gfzf_colors
    FZF_COLORS="
      --color=fg:-1
      --color=fg+:-1
      --color=bg:-1
      --color=bg+:${FZF_GRAY_COLOR}
      --color=preview-bg:-1
      --color=hl+:${FZF_YELLOW_COLOR}
      --color=hl:${FZF_YELLOW_COLOR}
      --color=info:${FZF_ORANGE_COLOR}
      --color=prompt:${FZF_ORANGE_COLOR}
      --color=pointer:${FZF_ORANGE_COLOR}
      --color=spinner:${FZF_ORANGE_COLOR}
      --color=header:#BBB529
      --color=border:-1
      --color=gutter:-1
    "
    export FZF_DEFAULT_OPTS="${FZF_OPTS} ${FZF_BINDINGS} ${FZF_COLORS}"

    # Provides nice coloring for preview window with clear
    # highlight of search result. To see other options use
    # bat --list-themes | fzf --preview="bat --theme={} --color=always --highlight-line 5:10 /path/to/file
    export BAT_THEME="Nord"

    # Custom preview for different commands. Example: cd **<TAB>
    # https://pragmaticpineapple.com/four-useful-fzf-tricks-for-your-terminal/#4-preview-files-before-selecting-them
    _fzf_comprun() {
      local command=$1
      shift

      case "$command" in
        cd) fzf "$@" --preview 'tree -C {} | head -200' ;;
        # export|unset) fzf "$@" --preview "eval 'echo \$'{}" ;;
        # ssh)          fzf "$@" --preview 'dig {}' ;;
        *)  fzf "$@" ;;
      esac
    }
fi



###-----------------   ${PATH} EXPORTS USED IN ~/.zshrc   ------------------###
USER_BIN="${HOME}/bin"
LOCAL_BIN="${HOME}/.local/bin"

### Uncomment and correctly define these if you are going to be using this software
#MYSQL_BIN="/path/to/mysql/bin"
#LATEX_BIN=/path/to/tex/bin
#MATLAB_BIN=/path/to/matlab/bin
#CUDA_BIN=/usr/local/cuda/bin
#CUDA_LIB64_HOME=/usr/local/cuda/lib64
#CUDA_CUPTI_LIB64_HOME=/usr/local/cuda/extras/CUPTI/lib64


### Configurations for nodejs version manager (nvm)
# Change 'NVM_DIR' and 'NODE_VERSION' as required
# Note: when 'NODE_VERSION' is set we don't use NVM as it slows down opening a new shell
NVM_DIR="$HOME/.nvm"
NODE_VERSION="16.7.0"
NODE_BIN="${NVM_DIR}/versions/node/v${NODE_VERSION}/bin"


### Configuration for Pyenv
PYENV_ROOT="${HOME}/.pyenv"
PYENV_BIN="${PYENV_ROOT}/bin"
PYENV_SHIMS="${PYENV_ROOT}/shims"
# Set to non-empty if you want to eval 'pyenv init'.
PYENV_INIT=""


### Configuration for Rust
RUST_BIN="${HOME}/.cargo/bin"
RUSTUP_HOME="${HOME}/.rustup"
CARGO_HOME="${HOME}/.cargo"

### Confuguration for Go
GOPATH="${HOME}/go"
GO_BIN="${GOPATH}/bin"

###------------------------------    SECRETS   --------------------------------###
# Home for defining secrets that are not used very often. Use in conjunction
# with 'add-secret-environment-variable.sh' and 'load-secret-environment-variable.sh'
# and then 'import-secrets' alias that will source directory below.
export ZSHENV_SECRETS=${HOME}/.zshenv-secrets


# List of names for commonly used secrets that should be exposed as env variables. Every
# such variale should be added to the keychain with 'add-secret-environment-variable.sh'
# and will be loaded in the '.zshrc' for every shell.
COMMON_SECRETS=(
  "GITHUB_TOKEN"
)
