- link:
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim: dotfiles/nvim/packer.nvim
    ~/.config/nvim/init.vim: dotfiles/nvim/init.vim
    ~/.config/nvim/lua: dotfiles/nvim/lua
    # ~/.config/nvim/general: dotfiles/vim/common/general
    # ~/.config/nvim/autoload: dotfiles/vim/common/autoload
    ~/.config/nvim/ftplugin: dotfiles/vim/common/ftplugin
    # ~/.config/nvim/ftdetect: dotfiles/vim/common/ftdetect
    ~/.config/nvim/colors: dotfiles/nvim/colors
    # ~/.config/nvim/syntax: dotfiles/vim/common/syntax
    # ~/.config/ultisnips: dotfiles/vim/common/ultisnips
    ~/.config/dictionaries-ik1614: misc/dictionaries
- shell:
    # Executed only if this file doesn't exist (to prevent overriding)
    - ["[ -f ~/.config/nvim/init-local.lua ] && echo '=> Already exists, skipping' || cp dotfiles/nvim/init-local.lua ~/.config/nvim/init-local.lua", Initialising init-local.lua]
