- link:
    ~/.config/nvim/init.lua: dotfiles/nvim/init.lua
    ~/.config/nvim/lazy-lock.json: dotfiles/nvim/lazy-lock.json
    ~/.config/nvim/lua: dotfiles/nvim/lua
    ~/.config/nvim/colors: dotfiles/nvim/colors
    ~/.config/nvim/after: dotfiles/nvim/after
    # ~/.config/nvim/general: dotfiles/vim/common/general
    ~/.config/nvim/autoload: dotfiles/vim/common/autoload
    ~/.config/nvim/ftplugin: dotfiles/vim/common/ftplugin
    ~/.config/nvim/ftdetect: dotfiles/vim/common/ftdetect
    # ~/.config/nvim/syntax: dotfiles/vim/common/syntax
    ~/.config/dictionaries-ik1614: misc/dictionaries
- shell:
    # Executed only if this file doesn't exist (to prevent overriding)
    - ["[ -f ~/.config/nvim/init-local.lua ] && echo '=> Already exists, skipping' || cp dotfiles/nvim/init-local.lua ~/.config/nvim/init-local.lua", Initialising init-local.lua]
