- link:
    ~/.vimrc: dotfiles/vim/vimrc
    ~/.vim/general: dotfiles/vim/common/general
    ~/.vim/autoload: dotfiles/vim/common/autoload
    ~/.vim/ftplugin: dotfiles/vim/common/ftplugin
    ~/.vim/themes: dotfiles/vim/common/themes
    ~/.vim/vim-plug: dotfiles/vim/common/vim-plug
    ~/.vim/coc-settings.json: dotfiles/vim/common/vim-plug/configs/coc-settings.json
    # This is sort of shared between NeoVim and Vim configs
    ~/.config/ultisnips: dotfiles/vim/common/ultisnips
- shell:
    # Executed only if this file doesn't exist (to prevent overriding)
    - ["[ -f ~/.vim/vimrc-local ] && echo '=> Already exists, skipping' || cp dotfiles/vim/vimrc-local ~/.vim/vimrc-local", Initialising .vimrc-local]
